<a href="https://colab.research.google.com/github/gmg5941/winter/blob/main/%EA%B3%BC%EC%A0%9C3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import warnings 
warnings.filterwarnings(action='ignore')
import numpy as np
import tensorflow as tf

In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [3]:
import os
os.chdir('/content/gdrive/MyDrive/data')

In [58]:
heart_train=pd.read_csv('heart attack train.csv')
heart_test=pd.read_csv('heart attack test.csv')
satisfaction_test=pd.read_csv('satisfaction_test.csv')
satisfaction_train=pd.read_csv('satisfaction_train.csv')

In [6]:
heart_train.head()

Unnamed: 0  age  sex  cp  trestbps  ...  oldpeak  slope  ca  thal  target
0          62   52    1   3       118  ...      0.0      1   0     1       1
1         127   67    0   2       152  ...      0.0      2   1     2       1
2         111   57    1   2       150  ...      0.2      2   1     3       1
3         287   57    1   1       154  ...      0.0      2   1     2       0
4         108   50    0   1       120  ...      1.1      2   0     2       1

[5 rows x 15 columns]

In [9]:
heart_test.head()

Unnamed: 0  age  sex  cp  trestbps  ...  oldpeak  slope  ca  thal  target
0         204   62    0   0       160  ...      6.2      0   3     3       0
1         159   56    1   1       130  ...      0.0      2   0     3       1
2         219   48    1   0       130  ...      0.0      2   2     3       0
3         174   60    1   0       130  ...      2.4      1   2     3       0
4         184   50    1   0       150  ...      2.6      1   0     3       0

[5 rows x 15 columns]

In [12]:
heart_train.isnull().sum()

Unnamed: 0    0
age           0
sex           0
cp            0
trestbps      0
chol          0
fbs           0
restecg       0
thalach       0
exang         0
oldpeak       0
slope         0
ca            0
thal          0
target        0
dtype: int64

In [13]:
heart_test.isnull().sum()

Unnamed: 0    0
age           0
sex           0
cp            0
trestbps      0
chol          0
fbs           0
restecg       0
thalach       0
exang         0
oldpeak       0
slope         0
ca            0
thal          0
target        0
dtype: int64

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
import statsmodels.api as sm

In [18]:
X_train=heart_train.drop(['target'], axis=1)
X_test=heart_test.drop(['target'], axis=1)
Y_train=heart_train['target']
Y_test=heart_test['target']

In [22]:
X_test.head()

Unnamed: 0  age  sex  cp  trestbps  ...  exang  oldpeak  slope  ca  thal
0         204   62    0   0       160  ...      0      6.2      0   3     3
1         159   56    1   1       130  ...      0      0.0      2   0     3
2         219   48    1   0       130  ...      1      0.0      2   2     3
3         174   60    1   0       130  ...      1      2.4      1   2     3
4         184   50    1   0       150  ...      0      2.6      1   0     3

[5 rows x 14 columns]

In [23]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [25]:
X_test_scaled=scaler.fit_transform(X_test)

In [26]:
log=LogisticRegression()
log.fit(X_train_scaled, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [27]:
print(log.score(X_train_scaled, Y_train))

0.9917355371900827


In [28]:
print(log.score(X_test_scaled, Y_test))

0.9672131147540983


In [31]:
pred=log.predict(X_test_scaled)

In [32]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, pred)

array([[28,  2],
       [ 0, 31]])

In [83]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, pred)

0.9672131147540983

In [34]:
satisfaction_train.head()

Unnamed: 0  Gender  ... Arrival Delay in Minutes  satisfaction
0      105527  Female  ...                     65.0     satisfied
1       82617  Female  ...                     37.0  dissatisfied
2       34069  Female  ...                      0.0     satisfied
3       18636    Male  ...                    567.0  dissatisfied
4       28693  Female  ...                     72.0     satisfied

[5 rows x 24 columns]

In [59]:
satisfaction_test['satisfaction'] = satisfaction_test['satisfaction'].map({'satisfied':1,'dissatisfied':0})

In [60]:
satisfaction_train['satisfaction'] = satisfaction_train['satisfaction'].map({'satisfied':1,'dissatisfied':0})

In [61]:
np.unique(satisfaction_train['Gender'])

array(['Female', 'Male'], dtype=object)

In [62]:
np.unique(satisfaction_train['Type of Travel'])

array(['Business travel', 'Personal Travel'], dtype=object)

In [63]:
np.unique(satisfaction_train['Class'])

array(['Business', 'Eco', 'Eco Plus'], dtype=object)

In [70]:
np.unique(satisfaction_train['Customer Type'])

array(['Loyal Customer', 'disloyal Customer'], dtype=object)

In [64]:
satisfaction_test['Gender'] = satisfaction_test['Gender'].map({'Female':1,'Male':0})
satisfaction_train['Gender'] = satisfaction_train['Gender'].map({'Female':1,'Male':0})

In [65]:
satisfaction_test['Class'] = satisfaction_test['Class'].map({'Business':2,'Eco':1,'Eco Plus':0})
satisfaction_train['Class'] = satisfaction_train['Class'].map({'Business':2,'Eco':1,'Eco Plus':0})

In [66]:
satisfaction_test['Type of Travel'] = satisfaction_test['Type of Travel'].map({'Business travel':1,'Personal Travel':0})
satisfaction_train['Type of Travel'] = satisfaction_train['Type of Travel'].map({'Business travel':1,'Personal Travel':0})

In [71]:
satisfaction_test['Customer Type'] = satisfaction_test['Customer Type'].map({'Loyal Customer':1,'disloyal Customer':0})
satisfaction_train['Customer Type'] = satisfaction_train['Customer Type'].map({'Loyal Customer':1,'disloyal Customer':0})

In [72]:
X_train2=satisfaction_train.drop(['satisfaction'], axis=1)
X_test2=satisfaction_test.drop(['satisfaction'], axis=1)
Y_train2=satisfaction_train['satisfaction']
Y_test2=satisfaction_test['satisfaction']

In [73]:
X_train2.head()

Unnamed: 0  Gender  ...  Departure Delay in Minutes  Arrival Delay in Minutes
0      105527       1  ...                          73                      65.0
1       82617       1  ...                          39                      37.0
2       34069       1  ...                           0                       0.0
3       18636       0  ...                         570                     567.0
4       28693       1  ...                          69                      72.0

[5 rows x 23 columns]

In [74]:
Y_train2.head()

0    1
1    0
2    1
3    0
4    1
Name: satisfaction, dtype: int64

In [75]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled2 = scaler.fit_transform(X_train2)
X_test_scaled2=scaler.fit_transform(X_test2)

In [78]:
X_train_scaled2

array([[ 1.08670043,  0.99012483,  0.47424442, ...,  0.50329518,
         1.55527976,  1.31260449],
       [ 0.47405889,  0.99012483,  0.47424442, ..., -0.26643465,
         0.65393562,  0.58105247],
       [-0.82417427,  0.99012483,  0.47424442, ..., -1.80589431,
        -0.37995913, -0.38564128],
       ...,
       [ 0.87913501,  0.99012483,  0.47424442, ..., -0.26643465,
        -0.03532755, -0.38564128],
       [ 1.50244631, -1.00997366,  0.47424442, ...,  1.273025  ,
        -0.37995913, -0.38564128],
       [-1.18822936, -1.00997366,  0.47424442, ..., -0.26643465,
        -0.37995913, -0.38564128]])

In [76]:
log2=LogisticRegression()
log2.fit(X_train_scaled2, Y_train2)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [79]:
pred2=log2.predict(X_test_scaled2)

In [80]:
confusion_matrix(Y_test2, pred2)

array([[4834, 1044],
       [1063, 6008]])

In [82]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test2, pred2)

0.8372847324117693